Feature/userpage
KirKozyrev/TaskManager pull request #13
Opened 2020-05-14 09:47 UTC by KirKozyrev

2020-05-14 11:03 UTC, pn-y requested changes

2020-05-14 11:03 UTC, pn-y commented on app/controllers/admin/application_controller.rb
> +    render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) if (forbidden?)
Избегай старого синтаксиса хешей когда можно

2020-05-14 11:03 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    new_user = User.find_by(first_name: user_attrs[:first_name])
first_name не уникальное поле. Не стоит по нему искать.

2020-05-14 11:03 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert_not new_user.nil?
assert new_user.present?

2020-05-14 11:03 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    searched_user = User.find(user.id);
точки с запятой не нужны :)

2020-05-14 11:03 UTC, pn-y commented on test/controllers/admin/users_controller_test.rb
> +    assert searched_user.nil?
assert_not User.exists?(id: user.id)

2020-05-14 11:03 UTC, pn-y commented on test/controllers/web/developers_controller_test.rb
> +    new_user = User.find_by(first_name: new_user_attrs[:first_name])
такой же коммент про поиск по далеко не уникальному полю

2020-05-14 20:54 UTC, artempartos requested changes

2020-05-14 20:54 UTC, artempartos commented on test/test_helper.rb
> +include AuthHelper
it should be included inside ActiveSupport::TestCase, not to the global namespace

2020-05-15 11:17 UTC, pn-y approved these changes

2020-05-15 13:51 UTC, merged