Feature/apiv1
KirKozyrev/TaskManager pull request #14
Opened 2020-05-18 13:53 UTC by KirKozyrev

2020-05-19 14:38 UTC, pn-y requested changes

2020-05-19 14:38 UTC, pn-y commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :html, :xml, :json
подними выше, в район. helper_method

2020-05-19 14:38 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all.
`all` - не нужный

2020-05-19 14:38 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    def show
?????

2020-05-19 14:38 UTC, pn-y commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
Или эта проверка будет проходить, или будет падать на 26 строке.

2020-05-20 06:07 UTC, KirKozyrev commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
`root@f7360c00a7ed:/task_manager# rails test test/controllers/api
Run options: --seed 54851

# Running:
.....

Finished in 1.535285s, 3.2567 runs/s, 10.4215 assertions/s.
5 runs, 16 assertions, 0 failures, 0 errors, 0 skips`

Всё проходит

2020-05-20 10:00 UTC, pn-y requested changes

2020-05-20 10:00 UTC, pn-y commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :html, :xml, :json
xml? html? wtf?

2020-05-20 10:00 UTC, pn-y commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
У тебя _эта_ проверка НЕ МОЖЕТ не проходить. 
Потому что это будет значить что на 26 строке не нашелся таск. А если он не найдется - будет эксепшон. А значит до этой строки не дойдет.

2020-05-20 11:41 UTC, KirKozyrev commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
Заменил на find_by - он не кидает исключений.

2020-05-21 17:57 UTC, pn-y approved these changes

2020-05-21 18:37 UTC, merged