Feature/devops
KirKozyrev/TaskManager pull request #20
Opened 2020-06-02 12:05 UTC by KirKozyrev

2020-06-04 10:54 UTC, pn-y commented
Выглядит так будто бы у тебя слишком много лишних файлов в репе.
Так не должно быть. Подумой как исправить

2020-06-12 12:42 UTC, pn-y requested changes

2020-06-12 12:42 UTC, pn-y commented on coverage/.last_run.json
> +{
не должно быть в репе

2020-06-12 12:42 UTC, pn-y commented on coverage/.resultset.json
> +{
не должно быть в репе

2020-06-12 12:42 UTC, pn-y commented on bin/rails
> +if ENV['RAILS_ENV'] == 'test'
Будто бы этого не должно быть здесь

2020-06-12 12:42 UTC, pn-y commented on .coveralls.yml
> +repo_token: cb3By1upKJctZv4k1S7XoTuFneDhjmnhP
спрятать в пепременную окружения

2020-06-12 12:42 UTC, pn-y commented on config/initializers/rollbar.rb
> +  config.access_token = '88a2e474717f4a4fa30665d87a08ee14'
спрятать в переменную окружения

2020-06-12 12:42 UTC, pn-y commented on config/newrelic.yml
> +  license_key: eu01xx442c267b5cf7fafdc68f09316eb7a5NRAL
ну ты понел

2020-06-14 18:26 UTC, artempartos commented
Таки все настроил )

2020-06-14 18:26 UTC, artempartos commented
👍

2020-07-08 14:56 UTC, merged