Feature/mailer
KirKozyrev/TaskManager pull request #23
Opened 2020-06-10 14:36 UTC by KirKozyrev

2020-06-12 12:59 UTC, pn-y requested changes

2020-06-12 12:59 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +      @user.errors.add(:password, "can't be empty")
Так абсолютно не стоит делать. Что тут плохо:
1. логика валидации
1. в контроллере
1. в рукопашную

2020-06-12 12:59 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    else
будто бы 3 ветки - чересчур

2020-06-12 12:59 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if @user.reset_sent_at < 24.hours.ago
Похоже что это логика не для контроллера

2020-06-12 12:59 UTC, pn-y commented on app/forms/reset_form.rb
> +    if user.blank?
Можно проверить любой емейл на наличие регистрации в приложении

2020-06-12 12:59 UTC, pn-y commented on app/models/user.rb
> +  def User.encrypt(string)
self.encrypt

2020-06-12 12:59 UTC, pn-y commented on app/models/user.rb
> +  def User.new_token
self.new_token

и все классовые методы поместить в конец

2020-06-12 12:59 UTC, pn-y commented on db/migrate/20200610082606_add_reset_to_users.rb
> +    add_column :users, :reset_digest, :string
А что если сгенерится одинаковый для двух юзеров?

2020-06-14 18:28 UTC, artempartos requested changes

2020-06-14 18:28 UTC, artempartos commented on db/migrate/20200610082606_add_reset_to_users.rb
> +    add_column :users, :reset_digest, :string
да, здесь надо индекс повесить

2020-06-14 19:59 UTC, pn-y requested changes

2020-06-14 19:59 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +  before_action :get_user,         only: [:edit, :update]
Какие то лишние пробелы

2020-06-14 19:59 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    @user_type = @user.type.downcase
Если послать неверный токен - будет 500

2020-06-14 19:59 UTC, pn-y commented on db/migrate/20200610082606_add_reset_to_users.rb
> +    add_index :reset_digest
Нужен индекс не простой, но уникальный :)

2020-06-14 19:59 UTC, pn-y commented on test/controllers/api/v1/tasks_controller_test.rb
> +      post :create, params: { task: task_attributes, format: :json }
format вне params должон быть

2020-06-14 19:59 UTC, pn-y commented on test/models/user_test.rb
> +    assert_not user_db[:reset_digest].nil?
Надо отдавать предпочтение синтаксису с точкой для работы с атрибутами

2020-06-15 21:04 UTC, pn-y requested changes

2020-06-15 21:04 UTC, pn-y commented on app/controllers/web/password_resets_controller.rb
> +    if @user.update(user_params)
А теперь здесь будет пятисотить если послать несуществующий токен

2020-06-15 21:04 UTC, pn-y commented on app/forms/reset_form.rb
> +    if user.blank?
^^^

2020-06-15 21:04 UTC, pn-y commented on db/schema.rb
> +    t.string "reset_digest"
schema.rb не обновил, индекса уникального не вижу здесь

2020-06-15 22:26 UTC, KirKozyrev commented on app/forms/reset_form.rb
> +    if user.blank?
> Можно проверить любой емейл на наличие регистрации в приложении

Не совсем понимаю, что тут надо поменять. 
Пользователь ищется по емейлу, если он не найден, то есть пустой, то валидация не пройдёт. Если найден, то есть не пустой, то всё отлично. 
Проверял неоднократно - всё работает.

2020-06-16 15:49 UTC, pn-y commented on app/forms/reset_form.rb
> +    if user.blank?
Заходит хакир. Вводит kir@kozyrev.com. Видит что такой емейл есть. Вводит ivan@ivanov.com - видит что такого емейла нет. Т.е. информация о емейлах имеющихся в системе считай общедоступна

2020-06-16 21:51 UTC, KirKozyrev commented on app/forms/reset_form.rb
> +    if user.blank?
Поправил этот момент. Пусть хакир локалхост пингует.

2020-06-18 14:50 UTC, pn-y requested changes

2020-06-18 14:50 UTC, pn-y commented on app/models/user.rb
> +    return true if self.reset_sent_at < 24.hours.ago
24 - в константу. Волшебное число же

2020-06-21 11:32 UTC, pn-y requested changes

2020-06-21 11:32 UTC, pn-y commented on app/models/user.rb
> +    return true if self.reset_sent_at < ONE_DAY_AGO
сравнение тебе вернет булево
в руби возвращается последнее выражение по-умолчанию

2020-06-21 11:32 UTC, pn-y commented on app/models/user.rb
> +    self.reset_token = User.new_token
Если такой токен ужен будет существовать - будет 500

2020-06-21 13:09 UTC, KirKozyrev commented on app/models/user.rb
> +    self.reset_token = User.new_token
Почему?

2020-06-25 20:50 UTC, pn-y requested changes

2020-06-25 20:50 UTC, pn-y commented on app/models/user.rb
> +    self.reset_token = User.new_token
Потому что есть уникальный индекс, но нет проверки уникальности в модели и при генерации токена

2020-06-25 22:34 UTC, KirKozyrev commented on app/models/user.rb
> +    self.reset_token = User.new_token
Добавил.

2020-07-06 20:29 UTC, artempartos approved these changes

2020-07-06 20:29 UTC, artempartos commented
rebase please

2020-07-08 14:07 UTC, merged