Feature/sidekiq
KirKozyrev/TaskManager pull request #24
Opened 2020-06-16 09:54 UTC by KirKozyrev

2020-06-18 14:53 UTC, pn-y requested changes

2020-06-18 14:53 UTC, pn-y commented on app/jobs/send_password_reset_notification_job.rb
> +    user = User.find_by(id: user_id);
Почему здесь вообще может не быть юзера?
Используй find

2020-06-18 14:53 UTC, pn-y commented on app/jobs/send_task_create_notification_job.rb
> +    task = Task.find_by(id: task_id)
Такая же штука. Ошибка просто замалчивается. Если вдруг тут небыло айдишника - бида значит какая то

2020-06-18 14:53 UTC, pn-y commented on app/jobs/send_task_delete_notification_job.rb
> +    user = User.find_by(id: task_author);
и тут

2020-06-18 14:53 UTC, pn-y commented on app/jobs/send_task_update_notification_job.rb
> +    task = Task.find_by(id: task_id)
ну ты понел

2020-06-21 11:21 UTC, pn-y requested changes

2020-06-21 11:21 UTC, pn-y commented on app/jobs/send_password_reset_notification_job.rb
> +    return if user.blank?
тут не может быть пустой юзер

2020-06-21 11:21 UTC, pn-y commented on app/jobs/send_task_create_notification_job.rb
> +    return if task.blank?
тут не может быть пустой юзер

2020-06-21 11:21 UTC, pn-y commented on app/jobs/send_task_update_notification_job.rb
> +    return if task.blank?
тут не может быть пустой юзер

2020-06-23 10:40 UTC, pn-y requested changes

2020-06-23 10:40 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +      SendTaskDeleteNotificationJob.perform_async(task_id, task_author)
А почему сигнатура изменилась? Почему автора нет в джобах выше, а здесь есть?

2020-06-23 11:05 UTC, KirKozyrev commented on app/controllers/api/v1/tasks_controller.rb
> +      SendTaskDeleteNotificationJob.perform_async(task_id, task_author)
На момент отправки письма этой задачи уже нет, поэтому нет возможности обратиться к автору.
Вот я решил этому джобу автора заранее передавать вторым аргументом.

2020-06-25 20:47 UTC, pn-y approved these changes

2020-06-25 20:47 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +      SendTaskDeleteNotificationJob.perform_async(task_id, task_author)
:+1:

2020-07-08 13:52 UTC, merged