Feature/models
KirKozyrev/TaskManager pull request #4
Opened 2020-04-26 18:42 UTC by KirKozyrev

2020-04-27 09:00 UTC, pn-y requested changes

2020-04-27 09:00 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id { 1 }
Не надо оперировать айдишниками, если есть возможность оперировать сущностями.
Не надо всегда создавать ассоциации - это приведет к неконтролируемому созданию сущностей по цепочке. Сделай их пустыми, и создай трейты для того создания автора или assignee.
Для создания остальных полей - используй sequence с алиасами, чтоб не приходилось каждый раз указывать какое-то-значение

2020-04-27 13:48 UTC, KirKozyrev commented on test/factories/tasks.rb
> +    author_id { 1 }
Проверь, пожалуйста.
До этого FactoryBot не использовал - мог запросто не то сделать.

2020-04-28 12:11 UTC, pn-y requested changes

2020-04-28 12:11 UTC, pn-y commented on test/factories/tasks.rb
> +    sequence(:author_id) {|n| n }
Еще раз 
```
Не надо оперировать айдишниками, если есть возможность оперировать сущностями.
Не надо всегда создавать ассоциации - это приведет к неконтролируемому созданию сущностей по цепочке. Сделай их пустыми, и создай трейты для того создания автора или assignee.
```
Айдишниками - все еще оперируешь.
Трейты для заполнения author и assignee - не сделал.

2020-04-28 12:11 UTC, pn-y commented on test/factories/tasks.rb
> +    sequence(:name) {|n| "Name#{n}" }
Создай отдельную фабрику с сиквенсами, чтоб потом использовать их. 
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#global-sequences
И алиасы к ним, чтоб ты мог просто написать description в фабрике и он заполнился из твоей sequence

2020-04-28 13:04 UTC, KirKozyrev commented on test/factories/tasks.rb
> +    sequence(:name) {|n| "Name#{n}" }
Создал отдельный файл с sequence и подключил его к остальным с помощью require_relative.
Так сработает или лучше все фабрики в одном модуле писать?

2020-04-28 13:04 UTC, KirKozyrev commented on test/factories/tasks.rb
> +    sequence(:author_id) {|n| n }
Написал трейты, но уверен, что что-то не то.
Не совсем понимаю, как избавиться от айдишников, и как это сделать с помощью трейтов.
Скинь, пожалуйста, пример или статью. В гугле я подобного применения трейтам не нашёл.

2020-04-29 11:56 UTC, Andrew8xx8 requested changes

2020-04-29 11:56 UTC, Andrew8xx8 commented on test/factories/global.rb
> +  sequence(:email, aliases: [:sender, :receiver]) { |n| "user#{n}@test.com" }
В одну строчку записанный код ухудшает читаемость.  используй do, end в данном случае для определения блока

2020-04-29 14:02 UTC, Andrew8xx8 requested changes

2020-04-29 14:02 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
Пустые тесты надо удалить, этот и еще четыре файла ниже

2020-04-30 08:34 UTC, Andrew8xx8 approved these changes

2020-04-30 10:13 UTC, merged